name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY_URL: ${{ format('ghcr.io/{0}', github.repository) }}

permissions:
  contents: read
  packages: write

jobs:
  build-base:
    uses: ./.github/workflows/reusable-build.yml
    strategy:
      fail-fast: false
      matrix:
        name:
          - "base-imgs/bullseye"
          - "base-imgs/bookworm"
          - "base-imgs/trixie"
    with:
      name: ${{ matrix.name }}
      build-base: true
    secrets: inherit

  build-imgs:
    needs: build-base
    uses: ./.github/workflows/reusable-build.yml
    strategy:
      fail-fast: false
      matrix:
        name:
          - archlinux
          - bookworm
          - bookworm-intel
          - bookworm-intel-2024.2
          - bookworm-mpich
          - bullseye
          - bullseye-intel
          - bullseye-openblas
          - trixie
          - tumbleweed
        clean-runner:
          - false
        include:
          - name:  bookworm-pgi-24-09
            clean-runner: true
          - name:  bullseye-pgi-21-03
            clean-runner: true
          - name:  nvidia-51.1
            clean-runner: true
          - name: jupyter
            clean-runner: false
            build-pyalf-full: true
            build-pyalf-doc: true
    with:
      name: ${{ matrix.name }}
      clean-runner: ${{ matrix.clean-runner }}
      build-alf-requirements: true
      build-pyalf-requirements: true
      build-pyalf-full: ${{ matrix.build-pyalf-full || false }}
      build-pyalf-doc: ${{ matrix.build-pyalf-doc || false }}
    secrets: inherit
